name: Debug Secrets

on:
  workflow_dispatch:

jobs:
  debug-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check DATABASE_URL secret
        run: |
          echo "DATABASE_URL length: ${#DATABASE_URL}"
          if [ -n "$DATABASE_URL" ]; then
            echo "DATABASE_URL is set (showing first 20 chars): ${DATABASE_URL:0:20}..."
          else
            echo "DATABASE_URL is NOT set or empty"
          fi
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      
      - name: List available secrets (masked)
        run: |
          echo "Available secrets context:"
          echo "GOOGLE_GENAI_API_KEY: ${{ secrets.GOOGLE_GENAI_API_KEY != '' }}"
          echo "DATABASE_URL: ${{ secrets.DATABASE_URL != '' }}"
          echo "PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY != '' }}"
