name: Test DATABASE_URL Secret Access

on:
  workflow_dispatch:

jobs:
  test-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Test DATABASE_URL Secret Access
        run: |
          echo "Testing DATABASE_URL secret access..."
          if [ -z "${{ secrets.DATABASE_URL }}" ]; then
            echo "❌ DATABASE_URL secret is EMPTY or NOT ACCESSIBLE"
            exit 1
          else
            echo "✅ DATABASE_URL secret is accessible"
            echo "Secret length: ${#DATABASE_URL}"
            echo "Secret starts with: ${DATABASE_URL:0:20}..."
          fi
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      
      - name: Test Secret in Environment Variable
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          echo "Environment variable test:"
          if [ -z "$DATABASE_URL" ]; then
            echo "❌ DATABASE_URL environment variable is EMPTY"
          else
            echo "✅ DATABASE_URL environment variable is set"
            echo "Length: ${#DATABASE_URL}"
          fi
